import Config

# 對於開發，我們禁用任何緩存並啟用
# 調試和代碼重新加載。
#
# watchers 配置可用於運行外部
# 觀察者到您的應用程序。例如，我們使用它
# 使用 webpack 重新編譯 .js 和 .css 源。

config :block_scout_web, BlockScoutWeb.Endpoint,
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :block_scout_web, BlockScoutWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/block_scout_web/views/.*(ex)$},
      ~r{lib/block_scout_web/templates/.*(eex)$}
    ]
  ]

config :block_scout_web, BlockScoutWeb.Tracer, env: "dev", disabled?: true

config :logger, :block_scout_web,
  level: :debug,
  path: Path.absname("logs/dev/block_scout_web.log")

config :logger, :api,
  level: :debug,
  path: Path.absname("logs/dev/api.log"),
  metadata_filter: [fetcher: :api]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

config :block_scout_web, :captcha_helper, BlockScoutWeb.CaptchaHelper
